server:
  port: 9090
spring: #配置连接数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_charge_sys?userUnicode=true&characterEncoding=UTF-8&userSSL=true;
    username: root
    password: hzx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    #配置日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true   #开启二级缓存
  mapper-locations: classpath*:/mapper/**/*.xml #配置 Mapper.xml 文件扫描的位置
  type-aliases-package: com.joolshe.chargesys.bean